# Generated by Django 5.0.6 on 2024-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
