# Generated by Django 5.0.6 on 2024-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='unique_id',
            field=models.CharField(default='97e9bffd8c', max_length=10, unique=True),
        ),
    ]
