# Generated by Django 5.0.6 on 2024-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_purchase_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unique_id',
            field=models.CharField(default='a79d6dc838', max_length=10, unique=True),
        ),
    ]
