# Generated by Django 5.0.6 on 2024-06-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_purchase_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unique_id',
            field=models.CharField(default='fe9ad8868a', max_length=10, unique=True),
        ),
    ]
