# Generated by Django 5.0.6 on 2024-06-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_purchase_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unique_id',
            field=models.CharField(default='c9fabc8aa1', max_length=10, unique=True),
        ),
    ]
