# Generated by Django 5.0.6 on 2024-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_purchase_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unique_id',
            field=models.CharField(default='e3d58ae8c7', max_length=10, unique=True),
        ),
    ]
